name: swork_raon
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.8+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  camera: ^0.9.1
  change_app_package_name: ^1.0.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.4.0
  fl_chart: ^0.10.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^4.3.0
  flutter_gen: ^4.2.0
  flutter_icons: ^1.1.0
  flutter_riverpod: ^2.0.0-dev.5
  flutter_signin_button: ^1.1.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7
  google_sign_in: ^5.3.0
  image: ^3.0.2
  image_picker: ^0.8.3+2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  motion_sensors: ^0.1.0
  page_transition: ^2.0.4
  path_provider: ^2.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Rapivet"
flutter:
  uses-material-design: true

  assets:
    - assets/images
    - assets/images/downbtns
    - assets/images/main
    - assets/images/result_plus
    - assets/images/test
    - assets/images/tutorial
    - assets/images/user_info

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/Noto.ttf
    - family: Gowun_dodum
      fonts:
        - asset: assets/fonts/Gowun_dodum.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash2.png
  fullscreen: true
