name: swork_raon
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  camera: ^0.9.1
  change_app_package_name: ^1.0.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.4.0
  fl_chart: ^0.10.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^4.3.0
  flutter_icons: ^1.1.0
  flutter_signin_button: ^1.1.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7
  google_sign_in: ^5.3.0
  image: ^3.0.2
  image_picker: ^0.8.3+2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  motion_sensors: ^0.1.0
  page_transition: ^2.0.4
  path_provider: ^2.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "Rapivet"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/temp.png
    - assets/black.JPG
    - assets/circleMark.png
    - assets/test_img/catdog.JPG
    - assets/test_img/cat.JPG
    - assets/test_img/dog.JPG
    - assets/test_img/ani1.png
    - assets/test_img/ani2.png
    - assets/test_img/dog2.JPG
    - assets/test_img/test_cat_Ad.JPG
    - assets/test_img/test_suspeita.JPG
    - assets/circle_blue.png
    - assets/circle_white.png
    - assets/temp_downbar.jpg
    - assets/facebook.png
    - assets/google.png
    - assets/apple.png
    - assets/facebook_sign.png
    - assets/google_sign.png
    - assets/apple_sign.png
    - assets/footmark.png
    - assets/updown_arrows.png
    - assets/icon_shop.png
    - assets/icon_vip.png
    - assets/guide.png
    - assets/guide_table_img.png
    - assets/dogface.png

    - assets/main_img/doctor_icon.png
    - assets/main_img/gray_mark.png
    - assets/main_img/icon_last_test.png
    - assets/main_img/icon_new_test.png
    - assets/main_img/result_btn.png
    - assets/main_img/page_on.png
    - assets/main_img/page_off.png

    - assets/userinfo_img/icon_delete.png
    - assets/userinfo_img/icon_edit.png
    - assets/userinfo_img/icon_news.png
    - assets/userinfo_img/icon_star.png
    - assets/userinfo_img/icon_vertical_line.png

    - assets/downbtns/down_main.png
    - assets/downbtns/down_result.png
    - assets/downbtns/down_result2.png
    - assets/downbtns/down_test.png

    - assets/downbtns/down_main_selected.png
    - assets/downbtns/down_result_selected.png
    - assets/downbtns/down_result2_selected.png
    - assets/downbtns/down_test_selected.png

    - assets/result_plus/normal_mark.png
    - assets/result_plus/suspect_mark.png
    - assets/result_plus/bar_blood.png
    - assets/result_plus/bar_glucose.png
    - assets/result_plus/bar_keton.png
    - assets/result_plus/bar_leukozyten.png
    - assets/result_plus/bar_nitrite.png
    - assets/result_plus/bar_ph.png
    - assets/result_plus/bar_protein.png
    - assets/result_plus/normal_guide.png
    - assets/result_plus/bar_normal_mark.png
    - assets/result_plus/bar_suspect_mark.png
    - assets/result_plus/grid.png

    - assets/tutorial/tuto1.jpg
    - assets/tutorial/tuto2.jpg
    - assets/tutorial/tutorial_end.png
    - assets/tutorial/cam_guide.png

    - assets/raon_welcome.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/Noto.ttf
    - family: Gowun_dodum
      fonts:
        - asset: assets/fonts/Gowun_dodum.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash2.png
  fullscreen: true
